import { useState, useEffect, useCallback, useRef } from 'react';
import { supabase } from '@/lib/supabase';
import { User, Session, AuthError, AuthChangeEvent } from '@supabase/supabase-js';
import { Database } from '@/types/database';
import { Platform } from 'react-native';
import { TABLES } from '@/constants/supabase';
import { posthog } from '@/constants/posthog';
import { logger } from '@/lib/logger';
import { AccountDisabledError, EmailNotVerifiedError, InvalidCredentialsError, TooManyAttemptsError } from '@/lib/errors';

type Profile = Database['public']['Tables']['profiles']['Row'];


interface UseAuthResult {
  user: User | null;
  session: Session | null;
  loading: boolean;
  authEvent: AuthChangeEvent | null;
  signUp: (
    email: string,
    password: string,
    userData?: Partial<Profile>
  ) => Promise<{ error: Error | null; data?: { userId: string } }>;
  signIn: (email: string, password: string) => Promise<{ error: Error | null }>;
  signOut: () => Promise<{ error: Error | null }>;
  resetPasswordForEmail: (email: string) => Promise<{ error: Error | null }>;
  updatePassword: (newPassword: string) => Promise<{ error: Error | null }>;
}

/**
 * Manages authentication state and provides sign-in, sign-up, sign-out,
 * password reset, and password update flows via Supabase Auth.
*/
export function useAuth(): UseAuthResult {
  const [user, setUser] = useState<User | null>(null);
  const [session, setSession] = useState<Session | null>(null);
  const [loading, setLoading] = useState<boolean>(true);
  const [authEvent, setAuthEvent] = useState<AuthChangeEvent | null>(null);

  // Use ref to avoid circular dependency with updateProfile
  const updateProfileRef = useRef<((updates: Partial<Profile>) => Promise<{ error: Error | null }>) | null>(null);

  useEffect(() => {
    // Platform-specific initialization
    const initializeAuth = async () => {
      try {
        const { data: { session: initialSession } } = await supabase.auth.getSession();
        setSession(initialSession);
        setUser(initialSession?.user ?? null);
      } catch (error) {
        // Don't crash the app, just log the error
        logger.error('Auth initialization error:', error);
      } finally {
        setLoading(false);
      }
    };

    initializeAuth();

    // Add this auth state listener
    const { data: { subscription } } = supabase.auth.onAuthStateChange(
      async (event, session) => {
        logger.info('Auth state changed:', { event, session });
        setAuthEvent(event);
        if (session) {
          posthog.identify(session.user.id, {
            email: session.user.email ?? '',
          });
        }
        setSession(session);
        setUser(session?.user ?? null);
        setLoading(false);
      }
    );

    return () => subscription.unsubscribe();
  }, []);

  const signUp = useCallback(async (
    email: string,
    password: string,
    userData?: Partial<Profile>
  ) => {
    setLoading(true);
    try {
      const { data, error } = await supabase.auth.signUp({
        email,
        password,
      });

      if (error) {
        return { error: new Error(error.message) };
      }

      // Wait for user to be authenticated and session to be established
      if (!data.user) return { error: new Error('User not found') };

      const userId = data.user.id;

      // Create profile manually after successful signup.
      // The invite_code is now generated by a Supabase trigger, so we don't
      // create it here or insert into the invites table manually.
      try {
        const profileData = {
          id: userId,
          email: data.user.email!,
          full_name: userData?.full_name || null,
          username: userData?.username || null,
          avatar_url: userData?.avatar_url || null,
          bio: userData?.bio || null,
        };

        const { error: profileError } = await supabase
          .from(TABLES.PROFILES)
          .upsert(profileData as never, { onConflict: 'id' });

        if (profileError) {
          logger.error('Error creating profile:', profileError);
          // Don't return error here as signup was successful
        }
      } catch (profileError) {
        logger.error('Error creating profile:', profileError);
        // Don't return error here as signup was successful
      }

      // Always return the userId so the caller can fetch the invite that
      // was created by the Supabase trigger.
      return { error: null, data: { userId } };

    } catch (error) {
      return { error: error as Error };
    } finally {
      setLoading(false);
    }
  }, []);

  const signIn = useCallback(async (email: string, password: string) => {
    setLoading(true);
    try {
      const { error, data } = await supabase.auth.signInWithPassword({
        email,
        password,
      });

      if (error) {
        // Handle specific error cases
        switch (error.message) {
          case 'Email not confirmed':
            throw new EmailNotVerifiedError();
          case 'Invalid login credentials':
            throw new InvalidCredentialsError();
          case 'Too many requests':
            throw new TooManyAttemptsError();
          default:
            // Check for other specific error patterns
            if (error.message.includes('email not confirmed')) {
              throw new EmailNotVerifiedError();
            }
            if (error.message.includes('invalid') && error.message.includes('credentials')) {
              throw new InvalidCredentialsError();
            }
            if (error.message.includes('too many')) {
              throw new TooManyAttemptsError();
            }
            // Generic auth error
            throw new Error(error.message || 'Sign in failed. Please try again.');
        }
      }

      // Additional check for email verification status
      if (data.user && !data.user.email_confirmed_at) {
        // Sign out the user since they're not verified
        await supabase.auth.signOut();
        throw new EmailNotVerifiedError();
      }

      return { error: null };
    } catch (error) {
      if (error instanceof EmailNotVerifiedError ||
        error instanceof AccountDisabledError ||
        error instanceof TooManyAttemptsError ||
        error instanceof InvalidCredentialsError) {
        return { error };
      }
      return { error: error as Error };
    } finally {
      setLoading(false);
    }
  }, []);

  const signOut = useCallback(async () => {
    setLoading(true);
    try {
      const { error } = await supabase.auth.signOut();

      if (!error) {
        setUser(null);
        setSession(null);
      }

      return { error: error ? new Error(error.message) : null };
    } catch (error) {
      return { error: error as Error };
    } finally {
      setLoading(false);
    }
  }, []);

  const resetPasswordForEmail = useCallback(async (email: string) => {
    try {
      // Build redirect URL based on platform
      const redirectTo = Platform.OS === 'web'
        ? `${window.location.origin}/reset-password`
        : `https://keepsafe.fortunealebiosu.dev/reset-password`

      const { error } = await supabase.auth.resetPasswordForEmail(email, {
        redirectTo,
      });

      if (error) {
        return { error: new Error(error.message) };
      }

      return { error: null };
    } catch (error) {
      return { error: error as Error };
    }
  }, []);

  const updatePassword = useCallback(async (newPassword: string) => {
    try {
      const { error } = await supabase.auth.updateUser({
        password: newPassword,
      });

      if (error) {
        return { error: new Error(error.message) };
      }

      return { error: null };
    } catch (error) {
      return { error: error as Error };
    }
  }, []);

  return {
    user,
    session,
    loading,
    authEvent,
    signUp,
    signIn,
    signOut,
    resetPasswordForEmail,
    updatePassword,
  };
}