import uuid
import calendar
import logging
from datetime import datetime, timezone
from typing import Any, Dict, List

from dateutil.relativedelta import relativedelta

from services.supabase_client import get_supabase_client
from services.queue_service import QueueService
from queue_constants import MONTHLY_DUMP_QUEUE_NAME, MONTHLY_DUMP_ENQUEUE_BATCH_SIZE
from database.tables import DatabaseTables

logger = logging.getLogger(__name__)


class MonthlyDumpEnqueueService:
    """Service to automatically bulk enqueue monthly dump jobs at the end of the month."""

    def __init__(self):
        self.supabase = get_supabase_client()
        self.queue_service = QueueService()
        self.queue_service.supabase = self.supabase
        self.queue_name = MONTHLY_DUMP_QUEUE_NAME
        self.batch_size = MONTHLY_DUMP_ENQUEUE_BATCH_SIZE

    def enqueue_eligible_users(self) -> None:
        """Find eligible users and enqueue their monthly dumps."""
        now_utc = datetime.now(timezone.utc)

        # Calculate the last day of the current month
        last_day_of_month = calendar.monthrange(now_utc.year, now_utc.month)[1]

        # We only want to be active during the last 3 days of the month (e.g. 29, 30, 31 for a 31-day month).
        # Which means today's day must be >= last_day_of_month - 2
        active_threshold = last_day_of_month - 2

        if now_utc.day < active_threshold:
            return  # Not in the active window, silently exit

        logger.info(
            "Within monthly dump active window, checking for eligible users",
            extra={"day": now_utc.day, "active_threshold": active_threshold},
        )

        # Find eligible users
        # Condition: monthly_dump_next_run IS NULL OR <= NOW()
        response = (
            self.supabase.table(DatabaseTables.PROFILES)
            .select("id")
            .or_(f"monthly_dump_next_run.is.null,monthly_dump_next_run.lte.{now_utc.isoformat()}")
            .limit(self.batch_size)
            .execute()
        )

        users = response.data
        if not users:
            logger.info("No eligible users found for monthly dump enqueueing")
            return

        logger.info("Eligible users found for monthly dump", extra={"user_count": len(users)})

        # Prepare dump data
        month_str = now_utc.strftime("%Y-%m")
        month_date = f"{month_str}-01"
        timezone_name = "UTC"

        # Compute next run (3rd to the last day of next month)
        next_month_date = now_utc + relativedelta(months=1)
        next_month_last_day = calendar.monthrange(next_month_date.year, next_month_date.month)[1]

        # 3rd to the last day = next_month_last_day - 2 days
        next_run_day = next_month_last_day - 2
        next_run_ts = next_month_date.replace(day=next_run_day, hour=0, minute=0, second=0, microsecond=0)

        dump_records = []
        messages = []
        user_ids_to_update = []

        for user in users:
            user_id = user["id"]
            monthly_dump_id = str(uuid.uuid4())

            dump_records.append({
                "id": monthly_dump_id,
                "user_id": user_id,
                "month": month_date,
                "timezone": timezone_name,
                "status": "pending",
                "slides": [],
                "photo_count": 0,
                "video_count": 0,
                "audio_count": 0,
                "grid_count": 0,
                "error": None,
                "created_at": now_utc.isoformat(),
                "updated_at": now_utc.isoformat(),
                "completed_at": None,
            })

            messages.append({
                "monthly_dump_id": monthly_dump_id,
                "user_id": user_id,
                "month": month_str,
                "timezone": timezone_name,
                "random_seed": None,  # Will be generated by queue processor
                "failure_count": 0,
                "created_at": now_utc.isoformat(),
            })

            user_ids_to_update.append(user_id)

        # 1. Upsert dummy entries in monthly_dumps. We use on_conflict to not overwrite if exists.
        try:
            self.supabase.table(DatabaseTables.MONTHLY_DUMPS).upsert(
                dump_records,
                on_conflict="user_id,month,timezone",
                ignore_duplicates=True
            ).execute()
        except Exception as e:
            logger.error("Failed to upsert pending monthly dumps", exc_info=True)
            return

        # 2. Enqueue the messages in bulk
        try:
            self.queue_service.send_message_batch(
                queue_name=self.queue_name,
                messages=messages
            )
        except Exception as e:
            logger.error("Failed to send message batch for monthly dumps", exc_info=True)
            return

        # 3. Update the profiles next run explicitly
        try:
            self.supabase.table(DatabaseTables.PROFILES).update({
                "monthly_dump_next_run": next_run_ts.isoformat()
            }).in_("id", user_ids_to_update).execute()
            logger.info(
                "Successfully enqueued monthly dumps and updated next run for users",
                extra={"user_count": len(user_ids_to_update), "next_run": next_run_ts.isoformat()},
            )
        except Exception as e:
            logger.error("Failed to update user profiles next run data", exc_info=True)
